import CustomProvider from '@/lib/graphqlclient';
import type { Metadata } from 'next';
import './globals.css';
import Navbar from '@/components/navbar/navbar';
import { ThemeProvider } from 'next-themes';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <CustomProvider>
                <body>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="dark"
                        enableSystem
                        disableTransitionOnChange
                    >
                        <Navbar />

                        {children}
                    </ThemeProvider>
                </body>
            </CustomProvider>
        </html>
    );
}
